### ISSUE TITLE
I am facing below warning once the execution is stopped for sp_whoisactive.. Should I be worried for the data due to this?

### ISSUE THREAD

**Issue by sumabris** [amachanic/sp_whoisactive#115]
Hi
I am facing below warning once the execution is stopped for sp_whoisactive.. Should I be worried for the data due to this?

Warning: The join order has been enforced because a local join hint is used.
Warning: Null value is eliminated by an aggregate or other SET operation

Thanks,
Suma B R

**Comment by M-Frenzel** [comment]
Hi @sumabris 

those warnings provide you with hints that you should be aware of in case the data is wrong or the query takes a long time.

`Warning: The join order has been enforced because a local join hint is used.` is printed because some JOINs are hinted, for example `INNER LOOP JOIN` instead of `INNER JOIN`. Normally you do not need those hints, sometimes they are in fact necessary to provide a fast or stable execution.

`Warning: Null value is eliminated by an aggregate or other SET operation` is printed usually because of the usage of aggregation functions such as `SUM` or `AVG`on columns that contain `NULL` values. `NULL` are not processed.

If you want to get rid of the last warning, you can add `SET ANSI_WARNINGS OFF` before executing the procedure.

I see no reason to be worried.
